import { useCallback, useEffect, useState } from 'react';
import type { Appointment, AppointmentStatus, WorkflowStatus, IntakeForm, ChartEntry, PhotoEntry, ChatMessage, LineNotification, AppConfig, HealthMetric, BreastfeedingRecord, AIConsultation, Escalation, EPDSResult, ConsentSignature, UsageBatch, MunicipalityReport, AuditLog, OperationalTask, PostCareSurvey, MidwifeAvailability } from './types';
import * as seed from './seed';
import { answerConsultation } from './ai';
import { generateBookingSlot } from './scheduling';

const KEY='mamoa_state_v7_full';
const migrateStoredCopy = (raw: string) => raw
 .split('予約入ってよかちゃん！').join('予約が入りました')
 .split('ままずけ屋').join('ママズケア');
const id=()=>crypto.randomUUID();
const now=()=>new Date().toISOString();
const workflowForStatus:Record<AppointmentStatus,WorkflowStatus>={
 '下書き':'DRAFT','申込':'SUBMITTED','要確認':'NEEDS_REVIEW','仮押さえ':'SLOT_HELD','予約済':'CONFIRMED','確定':'CONFIRMED','利用中':'IN_SERVICE','完了':'COMPLETED','キャンセル':'CANCELLED','無断キャンセル':'NO_SHOW'
};

export interface State {
 patients: typeof seed.seedPatients; appointments: Appointment[]; intakes: IntakeForm[]; charts: ChartEntry[]; photos: PhotoEntry[]; chats: ChatMessage[]; shifts: typeof seed.seedShifts; availability: MidwifeAvailability[]; lineNotifications: LineNotification[]; config: AppConfig;
 facilities: typeof seed.seedFacilities; midwives: typeof seed.seedMidwives; plans: typeof seed.seedPlans; coupons: typeof seed.seedCoupons; aiConsultations: AIConsultation[]; escalations: Escalation[]; epdsResults: EPDSResult[]; healthMetrics: HealthMetric[]; wearables: typeof seed.seedWearables; breastfeedingRecords: BreastfeedingRecord[]; usageBatches: UsageBatch[]; municipalityReports: MunicipalityReport[]; consents: ConsentSignature[]; auditLogs: AuditLog[];
 operationalTasks: OperationalTask[]; bookingChanges: typeof seed.seedBookingChanges; surveys: PostCareSurvey[]; dark:boolean;
}
function seedState():State { return {
 patients:seed.seedPatients,appointments:seed.seedAppointments,intakes:seed.seedIntakes,charts:seed.seedCharts,photos:seed.seedPhotos,chats:seed.seedChats,shifts:seed.seedShifts,availability:seed.seedAvailability,lineNotifications:seed.seedLineNotifications,config:seed.seedConfig,facilities:seed.seedFacilities,midwives:seed.seedMidwives,plans:seed.seedPlans,coupons:seed.seedCoupons,aiConsultations:seed.seedAIConsultations,escalations:seed.seedEscalations,epdsResults:seed.seedEPDS,healthMetrics:seed.seedHealthMetrics,wearables:seed.seedWearables,breastfeedingRecords:seed.seedBreastfeeding,usageBatches:seed.seedUsageBatches,municipalityReports:seed.seedReports,consents:seed.seedConsents,auditLogs:seed.seedAuditLogs,operationalTasks:seed.seedOperationalTasks,bookingChanges:seed.seedBookingChanges,surveys:seed.seedSurveys,dark:false
}; }
function load():State { try { const raw=localStorage.getItem(KEY); return raw?{...seedState(),...JSON.parse(migrateStoredCopy(raw))}:seedState(); } catch{return seedState();} }
export function hasOverlap(appointments:Appointment[],startISO:string,durationMin:number,excludeId?:string,facilityId?:string){const a=+new Date(startISO),ae=a+durationMin*60000;return appointments.some(x=>x.id!==excludeId&&x.workflowStatus!=='CANCELLED'&&x.status!=='キャンセル'&&(x.workflowStatus!=='SLOT_HELD'||!x.holdExpiresAt||+new Date(x.holdExpiresAt)>Date.now())&&(!facilityId||x.facilityId===facilityId)&&a<+new Date(x.start)+x.durationMin*60000&&+new Date(x.start)<ae);}
const audit=(actor:string,role:AuditLog['role'],action:string,target:string,reasonCode?:string):AuditLog=>({id:id(),at:now(),actor,role,action,target,reasonCode,immutable:true});
type SchedulableAppointment=Pick<Appointment,'patientId'|'facilityId'|'planId'|'start'|'durationMin'|'type'|'assignedMidwifeId'>;
function validateAppointmentSlot(state:State,appointment:SchedulableAppointment,excludeAppointmentId?:string){
 const plan=state.plans.find(p=>p.id===appointment.planId)||state.plans.find(p=>p.facilityId===appointment.facilityId&&p.type===appointment.type&&p.durationMin===appointment.durationMin);
 if(!plan)return{ok:false as const,reason:'予約プランを確認できませんでした。'};
 const generated=generateBookingSlot({start:appointment.start,plan,patientId:appointment.patientId,facility:state.facilities.find(f=>f.id===appointment.facilityId),midwives:state.midwives,availability:state.availability,appointments:state.appointments,excludeAppointmentId});
 if(!generated.available||!generated.selectedMidwifeId)return{ok:false as const,reason:'必要なスキル、対応可能時間、移動・バッファ、負荷上限を満たす助産師がいません。'};
 return{ok:true as const,assignedMidwifeId:generated.selectedMidwifeId};
}

export function useStore(){
 const [state,setState]=useState<State>(()=>load());
 useEffect(()=>{try{localStorage.setItem(KEY,JSON.stringify(state));}catch{}},[state]);
 const patch=<K extends keyof State>(key:K,value:State[K])=>setState(s=>({...s,[key]:value}));
 const addAudit=(actor:string,role:AuditLog['role'],action:string,target:string)=>setState(s=>({...s,auditLogs:[audit(actor,role,action,target),...s.auditLogs]}));
 const setDark=useCallback((dark:boolean)=>setState(s=>({...s,dark})),[]);
 const addChart=useCallback((c:Omit<ChartEntry,'id'>)=>setState(s=>({...s,charts:[{...c,id:id()},...s.charts],auditLogs:[audit(c.midwife,'midwife','カルテ保存',c.patientId),...s.auditLogs]})),[]);
 const updateAppointmentStatus=useCallback((appointmentId:string,status:Appointment['status'],actor='田村 南田')=>setState(s=>({...s,appointments:s.appointments.map(a=>a.id===appointmentId?{...a,status,workflowStatus:workflowForStatus[status],updatedAt:now()}:a),bookingChanges:[{id:id(),appointmentId,changedAt:now(),actor,type:'状態変更',before:s.appointments.find(a=>a.id===appointmentId)?.status||'',after:status,reasonCode:'MANUAL_STATUS'},...s.bookingChanges],auditLogs:[audit(actor,actor==='佐藤 みなみ'?'mother':'midwife',`予約${status}`,appointmentId,'MANUAL_STATUS'),...s.auditLogs]})),[]);
 const addChat=useCallback((m:Omit<ChatMessage,'id'>)=>setState(s=>({...s,chats:[...s.chats,{...m,id:id()}]})),[]);
 const addIntake=useCallback((i:Omit<IntakeForm,'id'>)=>setState(s=>({...s,intakes:[{...i,id:id()},...s.intakes]})),[]);
 const addPhoto=useCallback((p:Omit<PhotoEntry,'id'>)=>setState(s=>({...s,photos:[{...p,id:id()},...s.photos]})),[]);
 const holdSlot=useCallback((appointment:Omit<Appointment,'id'|'status'>)=>{
  let result:{ok:true;appointmentId:string;expiresAt:string}|{ok:false;reason:string}={ok:false,reason:'仮押さえできませんでした'};
  setState(s=>{if(hasOverlap(s.appointments,appointment.start,appointment.durationMin,undefined,appointment.facilityId)){result={ok:false,reason:'選択した時間は埋まりました。別の時間を選んでください。'};return s;}const slot=validateAppointmentSlot(s,appointment);if(!slot.ok){result=slot;return s;}const appointmentId=id(),expiresAt=new Date(Date.now()+10*60*1000).toISOString();result={ok:true,appointmentId,expiresAt};return{...s,appointments:[...s.appointments,{...appointment,assignedMidwifeId:slot.assignedMidwifeId,id:appointmentId,status:'仮押さえ',workflowStatus:'SLOT_HELD',holdExpiresAt:expiresAt,updatedAt:now()}],auditLogs:[audit('佐藤 みなみ','mother','予約枠を仮押さえ',appointmentId,'SLOT_HELD'),...s.auditLogs]};});return result;
 },[]);
 const bookAppointmentWithIntake=useCallback((appt:Omit<Appointment,'id'|'status'|'intakeId'>,intake:Omit<IntakeForm,'id'|'appointmentId'>,options?:{couponId?:string})=>{
  let result:{ok:true;appointmentId:string}|{ok:false;reason:string}={ok:false,reason:'予約できませんでした'};
  setState(s=>{if(appt.type!=='宿泊ケア'&&hasOverlap(s.appointments,appt.start,appt.durationMin,undefined,appt.facilityId)){result={ok:false,reason:'選択した時間は埋まりました。別の時間を選んでください。'};return s;}const slot=validateAppointmentSlot(s,appt);if(!slot.ok){result=slot;return s;}const aid=id(),iid=id(),createdAt=now();const facility=s.facilities.find(f=>f.id===appt.facilityId);const needsReview=intake.bleeding==='多量'||intake.breastCondition==='乳腺炎疑い';const status:AppointmentStatus=needsReview?'要確認':facility?.autoApprove?'確定':'申込';const workflowStatus=workflowForStatus[status];const newA:Appointment={...appt,assignedMidwifeId:slot.assignedMidwifeId,id:aid,status,workflowStatus,intakeId:iid,holdExpiresAt:undefined,termsVersion:s.config.termsVersion,termsSnapshot:`${s.config.termsVersion} を予約時点で保存`,cancellationPolicyVersion:s.config.cancellationPolicyVersion,updatedAt:createdAt};const newI:IntakeForm={...intake,id:iid,appointmentId:aid,submittedAt:createdAt};const coupon=options?.couponId?s.coupons.map(c=>c.id===options.couponId?{...c,remainingUses:Math.max(0,c.remainingUses-1)}:c):s.coupons;const reviewTask:OperationalTask|undefined=needsReview?{id:id(),appointmentId:aid,patientId:appt.patientId,queue:'専門判断',reasonCode:'INTAKE_RED_FLAG',title:'予約前問診の専門判断',detail:'健康上の赤旗があるため自動確定せず、助産師へ共有しました。',priority:'緊急',status:'未対応',createdAt,dueAt:new Date(Date.now()+30*60*1000).toISOString(),assignedRole:'midwife',assignedTo:'田村 南田'}:undefined;result={ok:true,appointmentId:aid};return{...s,appointments:[...s.appointments,newA],intakes:[newI,...s.intakes],coupons:coupon,operationalTasks:reviewTask?[reviewTask,...s.operationalTasks]:s.operationalTasks,consents:[{id:id(),patientId:appt.patientId,appointmentId:aid,type:'産後ケア利用同意',signedName:intake.consentSignature||intake.motherName,signedAt:createdAt,version:s.config.termsVersion||'terms-current',snapshot:newA.termsSnapshot},...s.consents],lineNotifications:[{id:id(),at:createdAt,channel:'official-line',to:intake.motherName,message:`${facility?.name??'施設'}の${appt.type}を${status==='確定'?'確定':'受け付け'}しました。マイページからいつでも確認できます。`,triggeredBy:'予約作成',deliveryStatus:'sent',webhookEventId:`local-${aid}`,retryCount:0,serviceMessage:true},...s.lineNotifications],auditLogs:[audit(intake.motherName,'mother','予約・問診',aid,'SELF_SERVICE_BOOKING'),...s.auditLogs]};});return result;
 },[]);
 const rescheduleAppointment=useCallback((appointmentId:string,start:string)=>{let ok=false;setState(s=>{const current=s.appointments.find(a=>a.id===appointmentId);if(!current||hasOverlap(s.appointments,start,current.durationMin,appointmentId,current.facilityId))return s;const slot=validateAppointmentSlot(s,{...current,start},appointmentId);if(!slot.ok)return s;ok=true;return{...s,appointments:s.appointments.map(a=>a.id===appointmentId?{...a,start,assignedMidwifeId:slot.assignedMidwifeId,updatedAt:now()}:a),bookingChanges:[{id:id(),appointmentId,changedAt:now(),actor:'佐藤 みなみ',type:'日時変更',before:current.start,after:start,reasonCode:'CUSTOMER_RESCHEDULE'},...s.bookingChanges],lineNotifications:[{id:id(),at:now(),channel:'official-line',to:'佐藤みなみさん',message:'予約日時を変更しました。新しい日時をご確認ください。',triggeredBy:'予約変更',deliveryStatus:'sent',retryCount:0},...s.lineNotifications],auditLogs:[audit('佐藤 みなみ','mother','予約日時変更',appointmentId,'CUSTOMER_RESCHEDULE'),...s.auditLogs]};});return ok;},[]);
 const cancelAppointment=useCallback((appointmentId:string,reason='家庭の都合')=>setState(s=>{const current=s.appointments.find(a=>a.id===appointmentId);if(!current)return s;return{...s,appointments:s.appointments.map(a=>a.id===appointmentId?{...a,status:'キャンセル',workflowStatus:'CANCELLED',updatedAt:now()}:a),bookingChanges:[{id:id(),appointmentId,changedAt:now(),actor:'佐藤 みなみ',type:'キャンセル',before:current.status,after:`キャンセル（${reason}）`,reasonCode:'CUSTOMER_CANCEL'},...s.bookingChanges],auditLogs:[audit('佐藤 みなみ','mother','予約キャンセル',appointmentId,'CUSTOMER_CANCEL'),...s.auditLogs]};}),[]);
 const updateIntake=useCallback((appointmentId:string,patchData:Partial<IntakeForm>)=>setState(s=>({...s,intakes:s.intakes.map(i=>i.appointmentId===appointmentId?{...i,...patchData,submittedAt:now()}:i),bookingChanges:[{id:id(),appointmentId,changedAt:now(),actor:'佐藤 みなみ',type:'問診更新',before:'前回回答',after:'最新回答',reasonCode:'SELF_UPDATE'},...s.bookingChanges],auditLogs:[audit('佐藤 みなみ','mother','問診を更新',appointmentId,'SELF_UPDATE'),...s.auditLogs]})),[]);
 const startService=useCallback((appointmentId:string)=>setState(s=>({...s,appointments:s.appointments.map(a=>a.id===appointmentId?{...a,status:'利用中',workflowStatus:'IN_SERVICE',serviceStartedAt:now()}:a),auditLogs:[audit('田村 南田','midwife','利用開始',appointmentId,'CARE_START'),...s.auditLogs]})),[]);
 const completeService=useCallback((appointmentId:string)=>setState(s=>({...s,appointments:s.appointments.map(a=>a.id===appointmentId?{...a,status:'完了',workflowStatus:'COMPLETED',serviceCompletedAt:now()}:a),lineNotifications:[{id:id(),at:now(),channel:'official-line',to:'ご利用者',message:'本日のケア、おつかれさまでした。1分アンケートと再予約をご利用いただけます。',triggeredBy:'利用完了',deliveryStatus:'queued',retryCount:0,serviceMessage:true},...s.lineNotifications],auditLogs:[audit('田村 南田','midwife','利用完了',appointmentId,'CARE_COMPLETE'),...s.auditLogs]})),[]);
 const updateTask=useCallback((taskId:string,status:OperationalTask['status'],resolutionNote?:string)=>setState(s=>({...s,operationalTasks:s.operationalTasks.map(t=>t.id===taskId?{...t,status,resolutionNote,updatedAt:now()}:t),auditLogs:[audit('担当スタッフ','admin',`業務タスク${status}`,taskId,'TASK_UPDATE'),...s.auditLogs]})),[]);
 const submitSurvey=useCallback((survey:Omit<PostCareSurvey,'id'|'submittedAt'>)=>setState(s=>({...s,surveys:[{...survey,id:id(),submittedAt:now()},...s.surveys],auditLogs:[audit('佐藤 みなみ','mother','利用後アンケート送信',survey.appointmentId,'POST_CARE_SURVEY'),...s.auditLogs]})),[]);
 const retryNotification=useCallback((notificationId:string)=>setState(s=>({...s,lineNotifications:s.lineNotifications.map(n=>n.id===notificationId?{...n,deliveryStatus:'retrying',retryCount:(n.retryCount||0)+1,errorMessage:undefined}:n),auditLogs:[audit('運営担当','admin','LINE通知を再送',notificationId,'NOTIFICATION_RETRY'),...s.auditLogs]})),[]);
 const saveAvailability=useCallback((entry:Omit<MidwifeAvailability,'id'|'createdAt'|'updatedAt'> & {id?:string})=>setState(s=>{const timestamp=now();const existing=entry.id?s.availability.find(x=>x.id===entry.id):undefined;const item:MidwifeAvailability={...entry,id:entry.id||id(),createdAt:existing?.createdAt||timestamp,updatedAt:timestamp};const availability=existing?s.availability.map(x=>x.id===item.id?item:x):[item,...s.availability];const role=entry.source==='admin'?'admin':'midwife';return{...s,availability,auditLogs:[audit(entry.createdBy,role,existing?'対応可能時間を更新':'対応可能時間を登録',`${entry.midwifeId}:${entry.kind}`,entry.source==='admin'?'AVAILABILITY_PROXY_EDIT':'AVAILABILITY_SELF_EDIT'),...s.auditLogs]};}),[]);
 const removeAvailability=useCallback((availabilityId:string,actor='田村 南田',role:AuditLog['role']='midwife')=>setState(s=>({...s,availability:s.availability.filter(x=>x.id!==availabilityId),auditLogs:[audit(actor,role,'対応可能時間を削除',availabilityId,role==='admin'?'AVAILABILITY_PROXY_EDIT':'AVAILABILITY_SELF_EDIT'),...s.auditLogs]})),[]);
 const askAI=useCallback((patientId:string,category:AIConsultation['category'],question:string)=>{const response=answerConsultation(question,category);const consultationId=id();const consultation:AIConsultation={id:consultationId,patientId,at:now(),category,question,answer:response.answer,confidence:response.confidence,sources:response.sources};let escalation:Escalation|undefined;if(response.escalate){escalation={id:id(),consultationId,patientId,createdAt:now(),reason:response.reason||'AI信頼度低下',severity:response.urgent?'緊急':'注意',status:'未対応',assignedMidwifeId:'mw1'};consultation.escalationId=escalation.id;}setState(s=>({...s,aiConsultations:[...s.aiConsultations,consultation],escalations:escalation?[escalation,...s.escalations]:s.escalations,lineNotifications:escalation?[{id:id(),at:now(),channel:'staff-line-works',to:'田村助産師',message:`AI相談からエスカレーション：${escalation.reason}`,triggeredBy:'AIトリアージ',deliveryStatus:'sent',retryCount:0},...s.lineNotifications]:s.lineNotifications}));return{...consultation,escalation};},[]);
 const saveEPDS=useCallback((patientId:string,answers:number[])=>{const score=answers.reduce((a,b)=>a+b,0),selfHarmAnswer=answers[9]||0,risk=selfHarmAnswer>0?'緊急':score>=9?'要フォロー':'低';const item:EPDSResult={id:id(),patientId,at:now(),answers,score,selfHarmAnswer,risk};setState(s=>({...s,epdsResults:[item,...s.epdsResults],escalations:risk==='低'?s.escalations:[{id:id(),patientId,createdAt:item.at,reason:selfHarmAnswer>0?'EPDS自傷念慮項目を検出':`EPDS ${score}点`,severity:selfHarmAnswer>0?'緊急':'注意',status:'未対応',assignedMidwifeId:'mw1'},...s.escalations]}));return item;},[]);
 const addHealthMetric=useCallback((m:Omit<HealthMetric,'id'|'abnormal'>)=>{const abnormal=(m.type==='収縮期血圧'&&m.value>=140)||(m.type==='拡張期血圧'&&m.value>=90)||(m.type==='体温'&&m.value>=38)||(m.type==='心拍'&&(m.value<50||m.value>120));setState(s=>({...s,healthMetrics:[{...m,id:id(),abnormal},...s.healthMetrics],escalations:abnormal?[{id:id(),patientId:m.patientId,createdAt:now(),reason:`${m.type} ${m.value}${m.unit} を検出`,severity:'緊急',status:'未対応',assignedMidwifeId:'mw1'},...s.escalations]:s.escalations}));},[]);
 const addBreastfeeding=useCallback((r:Omit<BreastfeedingRecord,'id'>)=>setState(s=>({...s,breastfeedingRecords:[{...r,id:id()},...s.breastfeedingRecords]})),[]);
 const resolveEscalation=useCallback((eid:string)=>setState(s=>({...s,escalations:s.escalations.map(e=>e.id===eid?{...e,status:'完了'}:e)})),[]);
 const confirmUsageBatch=useCallback((batchId:string)=>setState(s=>({...s,usageBatches:s.usageBatches.map(i=>i.id===batchId?{...i,status:'確定済',confirmedAt:now()}:i)})),[]);
 const submitReport=useCallback((reportId:string)=>setState(s=>({...s,municipalityReports:s.municipalityReports.map(r=>r.id===reportId?{...r,status:'提出済'}:r)})),[]);
 const toggleShift=useCallback((sid:string)=>setState(s=>({...s,shifts:s.shifts.map(x=>x.id===sid?{...x,closed:!x.closed}:x)})),[]);
 const updateConfig=useCallback((config:Partial<AppConfig>)=>setState(s=>({...s,config:{...s.config,...config}})),[]);
 const addLineNotification=useCallback((n:Omit<LineNotification,'id'>)=>setState(s=>({...s,lineNotifications:[{...n,id:id()},...s.lineNotifications]})),[]);
 const reset=useCallback(()=>{localStorage.removeItem(KEY);setState(seedState());},[]);
 return{state,setDark,addChart,updateAppointmentStatus,addChat,addIntake,addPhoto,holdSlot,bookAppointmentWithIntake,rescheduleAppointment,cancelAppointment,updateIntake,startService,completeService,updateTask,submitSurvey,retryNotification,saveAvailability,removeAvailability,askAI,saveEPDS,addHealthMetric,addBreastfeeding,resolveEscalation,confirmUsageBatch,submitReport,toggleShift,updateConfig,addLineNotification,addAudit,patch,reset};
}
